name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: stable
        id: go
      - uses: actions/checkout@v3
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
